ValueError: On field "integration_version" the following field constraints are set but not enforced: regex.  For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints